# Generated by Django 2.2.3 on 2019-07-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='domain',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
