# Generated by Django 2.2.3 on 2019-07-14 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_document_domain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Domains',
            new_name='Domain',
        ),
    ]
