# Generated by Django 2.2.3 on 2019-07-14 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0004_document_domain_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='domain_fk',
        ),
        migrations.AlterField(
            model_name='document',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy.Domain'),
        ),
    ]
